application: votesms
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py
